"""Remove weight_unit from user_preferences

Revision ID: 09e51a36eeef
Revises: c37a8c4a817f
Create Date: 2025-04-04 09:40:32.027838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09e51a36eeef'
down_revision = 'c37a8c4a817f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_workout_programs', 'program_data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_workout_programs', 'program_data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###
