"""Remove weight_unit from user_preferences

Revision ID: 09e51a36eeef
Revises: d8045dc7fc6c
Create Date: 2025-03-27 14:15:26.322575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09e51a36eeef'
down_revision = 'd8045dc7fc6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_workout_programs', 'program_data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    op.drop_column('user_preferences', 'weight_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column(
        'weight_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('saved_workout_programs', 'program_data',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###
