"""add card color to user preferences

Revision ID: 1b314eeeae49
Revises: cafaf7af569b
Create Date: 2025-03-11 02:48:27.488829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b314eeeae49'
down_revision = 'cafaf7af569b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('card_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'card_color')
    # ### end Alembic commands ###
