"""add_deletion_token_fields

Revision ID: 206236d30abd
Revises: c37a8c4a817f
Create Date: 2025-04-07 11:20:43.448985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '206236d30abd'
down_revision = 'c37a8c4a817f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('deletion_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_token_expires_at')
    op.drop_column('users', 'deletion_token')
    # ### end Alembic commands ###
