"""Add reward fields to models

Revision ID: 44a759b3820d
Revises: 
Create Date: 2023-09-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a759b3820d'
down_revision = '1d70d8121e97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add workout_templates_unlocked to user_profiles
    op.add_column('user_profiles', sa.Column('workout_templates_unlocked', sa.Boolean(), nullable=True, server_default='false'))
    
    # Add stats_features_unlocked to user_profiles  
    op.add_column('user_profiles', sa.Column('stats_features_unlocked', sa.Boolean(), nullable=True, server_default='false'))
    
    # Add reward_claimed to user_achievements
    op.add_column('user_achievements', sa.Column('reward_claimed', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns added in upgrade
    op.drop_column('user_achievements', 'reward_claimed')
    op.drop_column('user_profiles', 'stats_features_unlocked')
    op.drop_column('user_profiles', 'workout_templates_unlocked')
    # ### end Alembic commands ###
