"""add_weight_unit_to_routine

Revision ID: 4aba66bd52fd
Revises: a554eb8186aa
Create Date: 2025-03-30 22:11:36.247609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aba66bd52fd'
down_revision = 'a554eb8186aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column(
        'weight_unit', sa.String(), nullable=True))
    op.execute("UPDATE routines SET weight_unit = 'kg' WHERE weight_unit IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'weight_unit')
    # ### end Alembic commands ###
