"""Add created_at and description to Routine model

Revision ID: 57933cfabf1f
Revises: 86fcec28dc21
Create Date: 2025-04-04 09:14:33.162753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57933cfabf1f'
down_revision = '86fcec28dc21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('routines', sa.Column('description', sa.String(), nullable=True))
    # Set default value for created_at for existing records
    op.execute("UPDATE routines SET created_at = NOW() WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'description')
    op.drop_column('routines', 'created_at')
    # ### end Alembic commands ###
