"""add_animation_preferences_to_user_profile

Revision ID: 75d8c83bc04f
Revises: 99b5731f09fb
Create Date: 2025-04-16 20:14:35.891647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75d8c83bc04f'
down_revision = '99b5731f09fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('enable_animations', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_profiles', sa.Column('animation_style', sa.String(), nullable=True, server_default='subtle'))
    op.add_column('user_profiles', sa.Column('animation_speed', sa.String(), nullable=True, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'animation_speed')
    op.drop_column('user_profiles', 'animation_style')
    op.drop_column('user_profiles', 'enable_animations')
    # ### end Alembic commands ###
