"""Add oauth_provider and signup_method to users table

Revision ID: 8efdf99ed532
Revises: 34ac6256b074
Create Date: 2025-09-22 22:06:59.554877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8efdf99ed532'
down_revision = '34ac6256b074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add oauth_provider column to users table
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    
    # Add signup_method column to users table with default value
    op.add_column('users', sa.Column('signup_method', sa.String(), nullable=True, server_default='email'))
    
    # Update existing users based on their hashed_password
    op.execute("UPDATE users SET oauth_provider = 'google', signup_method = 'google' WHERE hashed_password = 'google_oauth'")
    op.execute("UPDATE users SET oauth_provider = 'apple', signup_method = 'apple' WHERE hashed_password = 'apple_oauth'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns that were added in upgrade
    op.drop_column('users', 'signup_method')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
