"""Add use_custom_card_color and frequency_goal fields to UserProfile

Revision ID: 95048c708341
Revises: d5493bc24c6e
Create Date: 2025-04-12 00:11:35.521963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95048c708341'
down_revision = 'd5493bc24c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('use_custom_card_color', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_profiles', sa.Column('frequency_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'frequency_goal')
    op.drop_column('user_profiles', 'use_custom_card_color')
    # ### end Alembic commands ###
