"""add_emoji_preferences_to_user_profile

Revision ID: 99b5731f09fb
Revises: 503abd8b7cbc
Create Date: 2025-04-15 19:03:20.679304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99b5731f09fb'
down_revision = '503abd8b7cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('show_profile_emoji', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user_profiles', sa.Column('profile_emoji', sa.String(), nullable=True, server_default='🏋️‍♂️'))
    op.add_column('user_profiles', sa.Column('emoji_animation', sa.String(), nullable=True, server_default='lift'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'emoji_animation')
    op.drop_column('user_profiles', 'profile_emoji')
    op.drop_column('user_profiles', 'show_profile_emoji')
    # ### end Alembic commands ###
