"""add_weight_unit_to_workout

Revision ID: a554eb8186aa
Revises: 09e51a36eeef
Create Date: 2025-03-30 21:49:57.010326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a554eb8186aa'
down_revision = '09e51a36eeef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column(
        'weight_unit', sa.String(), nullable=True))
    op.execute("UPDATE workouts SET weight_unit = 'kg' WHERE weight_unit IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'weight_unit')
    # ### end Alembic commands ###
