"""add workout_frequency_goal to WorkoutPreferences

Revision ID: b0bcb3c310b0
Revises: cd179438568e
Create Date: 2025-04-04 11:38:53.329433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0bcb3c310b0'
down_revision = 'cd179438568e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_preferences', sa.Column('workout_frequency_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_preferences', 'workout_frequency_goal')
    # ### end Alembic commands ###