"""add_is_template_to_workout

Revision ID: bb037c8ce561
Revises: 4aba66bd52fd
Create Date: 2025-03-31 00:28:33.997269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb037c8ce561'
down_revision = '4aba66bd52fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column(
        'is_template', sa.Boolean(), nullable=True))
    op.execute("UPDATE workouts SET is_template = FALSE WHERE is_template IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_template')
    # ### end Alembic commands ###
