"""Add summary frequency to user preferences

Revision ID: cafaf7af569b
Revises: 1c6fcfce4f45
Create Date: 2025-03-09 16:23:45.958208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafaf7af569b'
down_revision = '1c6fcfce4f45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('summary_frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'summary_frequency')
    # ### end Alembic commands ###
