"""Add saved workout programs table

Revision ID: ce4233aefb7a
Revises: 1b314eeeae49
Create Date: 2025-03-26 17:57:46.255387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4233aefb7a'
down_revision = '1b314eeeae49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_workout_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('completed_weeks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_workout_programs_id'), 'saved_workout_programs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_workout_programs_id'), table_name='saved_workout_programs')
    op.drop_table('saved_workout_programs')
    # ### end Alembic commands ###
