"""Add streak fields to UserProfile

Revision ID: d5493bc24c6e
Revises: f79e193d40e7
Create Date: 2025-04-11 00:55:04.137674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5493bc24c6e'
down_revision = 'f79e193d40e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the missing columns to user_profiles table
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user_profiles', sa.Column('best_streak', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user_profiles', sa.Column('last_workout_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the added columns if needed to downgrade
    op.drop_column('user_profiles', 'last_workout_date')
    op.drop_column('user_profiles', 'best_streak')
    op.drop_column('user_profiles', 'current_streak')
    # ### end Alembic commands ###