"""add_routine_folders

Revision ID: da4d249c9cf7
Revises: bb037c8ce561
Create Date: 2025-03-31 01:00:07.231255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4d249c9cf7'
down_revision = 'bb037c8ce561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column(
        'folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routines', 'routine_folders', [
                          'folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routines', type_='foreignkey')
    op.drop_column('routines', 'folder_id')
    # ### end Alembic commands ###
