"""add_workout_templates

Revision ID: dbfffbcf92e5
Revises: 206236d30abd
Create Date: 2025-04-07 18:02:35.568565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbfffbcf92e5'
down_revision = '206236d30abd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - properly adjusted for adding only the new tables ###
    op.create_table('workout_templates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('creator', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('is_premium', sa.Boolean(), default=False, nullable=False),
        sa.Column('workouts', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('user_unlocked_templates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('template_ids', postgresql.JSON(astext_type=sa.Text()), default=sa.text("'[]'::json"), nullable=False),
        sa.Column('last_updated', sa.DateTime(), default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - properly adjusted for removing only the added tables ###
    op.drop_table('user_unlocked_templates')
    op.drop_table('workout_templates')
    # ### end Alembic commands ###
