"""add fields to saved_workout_programs

Revision ID: e15969de98b1
Revises: 7ec0f5f8f7a7
Create Date: 2025-04-05 23:46:49.023854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e15969de98b1'
down_revision = '7ec0f5f8f7a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_workout_programs', sa.Column('name', sa.String(), nullable=True, server_default='Workout Program'))
    op.add_column('saved_workout_programs', sa.Column('description', sa.String(), nullable=True, server_default=''))
    op.add_column('saved_workout_programs', sa.Column('category', sa.String(), nullable=True, server_default='General'))
    op.add_column('saved_workout_programs', sa.Column('exercise_weights', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('saved_workout_programs', sa.Column('exercise_notes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('saved_workout_programs', sa.Column('weight_unit', sa.String(), nullable=True, server_default='kg'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_workout_programs', 'weight_unit')
    op.drop_column('saved_workout_programs', 'exercise_notes')
    op.drop_column('saved_workout_programs', 'exercise_weights')
    op.drop_column('saved_workout_programs', 'category')
    op.drop_column('saved_workout_programs', 'description')
    op.drop_column('saved_workout_programs', 'name')
    # ### end Alembic commands ###
