"""Add selected_badges to UserProfile

Revision ID: f79e193d40e7
Revises: 1df0484b9779
Create Date: 2025-04-10 22:20:13.003487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f79e193d40e7'
down_revision = '1df0484b9779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('selected_badges', postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'selected_badges')
    # ### end Alembic commands ###
