"""Add profile picture and user preferences

Revision ID: fe97a604b853
Revises: fb8db323f472
Create Date: 2025-03-05 17:30:25.108040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe97a604b853'
down_revision: Union[str, None] = 'fb8db323f472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sets_id', table_name='sets')
    op.drop_table('sets')
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_workouts_id', table_name='workouts')
    op.drop_table('workouts')
    op.drop_index('ix_custom_exercises_category',
                  table_name='custom_exercises')
    op.drop_index('ix_custom_exercises_id', table_name='custom_exercises')
    op.drop_index('ix_custom_exercises_name', table_name='custom_exercises')
    op.drop_table('custom_exercises')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('hashed_password', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('custom_exercises',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('category', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='custom_exercises_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='custom_exercises_pkey')
                    )
    op.create_index('ix_custom_exercises_name',
                    'custom_exercises', ['name'], unique=False)
    op.create_index('ix_custom_exercises_id',
                    'custom_exercises', ['id'], unique=False)
    op.create_index('ix_custom_exercises_category',
                    'custom_exercises', ['category'], unique=False)
    op.create_table('workouts',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('date', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('start_time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('end_time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('bodyweight', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('notes', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='workouts_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='workouts_pkey')
                    )
    op.create_index('ix_workouts_id', 'workouts', ['id'], unique=False)
    op.create_table('exercises',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('category', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('is_cardio', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('workout_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['workout_id'], ['workouts.id'], name='exercises_workout_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
                    )
    op.create_index('ix_exercises_id', 'exercises', ['id'], unique=False)
    op.create_table('sets',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('weight', sa.DOUBLE_PRECISION(
                        precision=53), autoincrement=False, nullable=True),
                    sa.Column('reps', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('duration', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('intensity', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('notes', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('exercise_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['exercise_id'], ['exercises.id'], name='sets_exercise_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='sets_pkey')
                    )
    op.create_index('ix_sets_id', 'sets', ['id'], unique=False)
    # ### end Alembic commands ###
